openapi: 3.0.3
info:
  title: Vulpress API
  description: A simple API to allow server-client communications
  contact:
    name: Szabolcs Bazil Papp
    email: papp.szabolcs.bazil@gmail.com
  version: 1.0.0

tags:
  - name: Auth
    description: Authentication related endpoints
  - name: Registration
    description: Registration related endpoints
  - name: View
    description: Endpoints for loading view specific information
  - name: Article
    description: Article categorisation and CRUD operations
  - name: Schedule
    description: CRUD operations for schedules
  - name: Image
    description: Endpoints for accessing images

paths:

  # Auth
  /auth/login:
    post:
      summary: Attempts authentication.
      description: |
        Submits an username-password authentication request for login purposes.
      tags:
        - Auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
  /auth:
    get:
      summary: Checks for authentication.
      description: |
        Pings the server with the authentication token included as a bearer token to check
        for its validity.
      tags:
        - Auth
      operationId: isAuthenticated
      responses:
        '200':
          description: Ok
        '403':
          description: Unauthorized

  # Registration
  /registration:
    post:
      summary: Submits a registration.
      description: |
        ...
      tags:
        - Registration
      operationId: registerAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '201':
          description: Registration accepted
        '409':
          description: Username taken
        '422':
          description: Inappropriate properties
    get:
      summary: Activates a registration.
      description: |
        ...
      tags:
        - Registration
      operationId: verifyAccount
      parameters:
        - in: query
          name: registrationToken
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: |
            Idempotent OK.
            
            Attempting to verify a valid registration token always returns with this response.
        '400':
          description: Unknown registration

        # View
  /view/app:
    get:
      summary: Returns the state of the app bar.
      description: |
        Returns the state of the app bar, including the title of the application, the
        logged-in status (for rendering the profile drop-down menu), and the available
        UiActions in the hamburger menu.
      tags:
        - View
      operationId: getAppBar
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppBarModel'
  
  /view/{viewName}/actions:
    get:
      summary: Returns the available actions for a given view.
      description: |
        Returns the UiActions (usually represented as buttons) for a given view.
      tags:
        - View
      operationId: getActions
      parameters:
        - in: path
          name: viewName
          schema:
            type: string
          required: true
        - in: query
          name: pageName
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UiAction'
        '404':
          description: Unknown view name

  # Article
  /categories:
    get:
      summary: List all categories
      description: |
        Returns a list of categories available with the provided
        authorisation (regular and anonymous users may only receive a
        subset of categories available to administrators).
      tags:
        - Article
      operationId: listCategories
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      summary: Create a new category
      description: |
        Creates a new, empty category. The category's URL-safe unique code
        is generated server side, and must be unique.
      tags:
        - Article
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Category has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          description: Insufficient authorization for category creation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Category already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /categories/{category}:
    get:
      summary: Return the first page of articles in a category
      description: |
        ...
      tags:
        - Article
      operationId: getRecentArticles
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticlePreview'
        '401':
          description: Insufficient authorization to fetch category contents.
        '404':
          description: Unknown category

    delete:
      summary: Delete a category
      description: |
        Deletes a category, moving its contents to the archived category. The archived category
        may not be deleted.
      tags:
        - Article
      operationId: deleteCategory
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Category deleted
        '401':
          description: Insufficient authorization to delete category.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    post:
      summary: Creates a new article in this category
      description: |
        ...
      tags:
        - Article
      operationId: uploadArticle
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: |
                    The desired title of the article
                issued:
                  type: string
                  format: date
                  description: |
                    The date for which this article is issued, may be null.
                author:
                  type: string
                  description: |
                    The name of the article's author. If null, the uploader is considered the author.
                description:
                  type: string
                  description: |
                    Succinct description for the article.
                documentFile:
                  type: string
                  format: binary
              required: [ title, issued, author, description, documentFile ]
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDetail'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /categories/{category}/{page}:
    get:
      summary: Return the Nth page of a categories articles
      description: |
        ...
      tags:
        - Article
      operationId: getArticles
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticlePreview'
        '401':
          description: Insufficient authorization to fetch category contents.
        '404':
          description: Unknown category

  /articles/{article}:
    get:
      summary: Load the contents of an article
      description: |
        ...
      tags:
        - Article
      operationId: getArticle
      parameters:
        - in: path
          name: article
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDetail'
        '404':
          description: Not found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    delete:
      summary: Delete an article
      description: |
        ...
      tags:
        - Article
      operationId: deleteArticle
      parameters:
        - in: path
          name: article
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '404':
          description: Not found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /articles:
    post:
      summary: Moves an article
      description: |
        ...
      tags:
        - Article
      operationId: moveArticle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleMoveRequest'
      responses:
        '200':
          description: Ok
        '404':
          description: Not found
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

    get:
      summary: Searches articles
      description: |
        Finds articles matching the filter criteria provided as query parameters.
      tags:
        - Article
      operationId: findArticles
      parameters:
        - in: query
          name: contains
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticlePreview'

components:
  schemas:

    AuthenticationRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: [ username, password ]
    AuthenticationResponse:
      type: object
      properties:
        token:
          type: string

    Category:
      type: object
      properties:
        code:
          type: string
          description: |
            URL-safe unique identifier.
          example: homilies
        title:
          type: string
          example: Homilies
        description:
          type: string
      required: [ code, displayValue ]

    ArticlePreview:
      type: object
      properties:
        code:
          type: string
          description: |
            URL-safe unique identifier.
        title:
          type: string
        description:
          type: string
        issueDate:
          type: string
          format: date
        author:
          type: string
        thumbnail:
          type: string
          format: uuid
          description: |
            The unique identifier of the image to be as thumbnail for
            the article.
      required: [ id, title, description ]

    ArticleDetail:
      type: object
      properties:
        code:
          type: string
          description: |
            URL-safe unique identifier.
        title:
          type: string
        issueDate:
          type: string
          format: date
        author:
          type: string
        paragraphs:
          type: array
          items:
            $ref: '#/components/schemas/Paragraph'
      required: [ id, code, title, paragraphs ]

    Paragraph:
      type: object
      properties:
        title:
          type: string
        text:
          type: string
        image:
          type: string
          format: uuid

    ArticleMoveRequest:
      type: object
      properties:
        article:
          type: string
        targetCategory:
          type: string
      required: [ article, targetCategory ]

    AppBarModel:
      type: object
      properties:
        appName:
          type: string
        loggedIn:
          type: boolean
          default: false
        availableCategories:
          type: array
          items:
            $ref: '#/components/schemas/UiAction'

    UiAction:
      type: object
      properties:
        code:
          type: string
        title:
          type: string
        colour:
          type: string
        icon:
          type: string
        disabled:
          type: boolean
          default: false
      required: [ code, title, disabled ]

    ApiError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string
